/* tslint:disable */
/* eslint-disable */
/**
 * HFHS Regi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddHistoryQuery
 */
export interface AddHistoryQuery {
    /**
     * クラス名
     * @type {string}
     * @memberof AddHistoryQuery
     */
    className: string;
    /**
     * 購入金額
     * @type {number}
     * @memberof AddHistoryQuery
     */
    total: number;
    /**
     * お釣り
     * @type {number}
     * @memberof AddHistoryQuery
     */
    change: number;
    /**
     * 購入商品
     * @type {string}
     * @memberof AddHistoryQuery
     */
    product: string;
}

/**
 * Check if a given object implements the AddHistoryQuery interface.
 */
export function instanceOfAddHistoryQuery(value: object): value is AddHistoryQuery {
    if (!('className' in value) || value['className'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('change' in value) || value['change'] === undefined) return false;
    if (!('product' in value) || value['product'] === undefined) return false;
    return true;
}

export function AddHistoryQueryFromJSON(json: any): AddHistoryQuery {
    return AddHistoryQueryFromJSONTyped(json, false);
}

export function AddHistoryQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddHistoryQuery {
    if (json == null) {
        return json;
    }
    return {
        
        'className': json['class_name'],
        'total': json['total'],
        'change': json['change'],
        'product': json['product'],
    };
}

export function AddHistoryQueryToJSON(value?: AddHistoryQuery | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'class_name': value['className'],
        'total': value['total'],
        'change': value['change'],
        'product': value['product'],
    };
}

