/* tslint:disable */
/* eslint-disable */
/**
 * HFHS Regi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthStatus
 */
export interface AuthStatus {
    /**
     * result
     * @type {string}
     * @memberof AuthStatus
     */
    isLogin?: string;
}

/**
 * Check if a given object implements the AuthStatus interface.
 */
export function instanceOfAuthStatus(value: object): value is AuthStatus {
    return true;
}

export function AuthStatusFromJSON(json: any): AuthStatus {
    return AuthStatusFromJSONTyped(json, false);
}

export function AuthStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'isLogin': json['isLogin'] == null ? undefined : json['isLogin'],
    };
}

export function AuthStatusToJSON(value?: AuthStatus | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'isLogin': value['isLogin'],
    };
}

