/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface History
 */
export interface History {
    /**
     * 決済ID(ランダムなIDが自動指定)
     * @type {string}
     * @memberof History
     */
    paymentId?: string;
    /**
     * クラス名
     * @type {string}
     * @memberof History
     */
    className?: string;
    /**
     * タイムスタンプ
     * @type {string}
     * @memberof History
     */
    timestamp?: string;
    /**
     * 購入金額
     * @type {number}
     * @memberof History
     */
    total?: number;
    /**
     * お釣り
     * @type {number}
     * @memberof History
     */
    change?: number;
    /**
     * 購入商品
     * @type {string}
     * @memberof History
     */
    product?: string;
}

/**
 * Check if a given object implements the History interface.
 */
export function instanceOfHistory(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HistoryFromJSON(json: any): History {
    return HistoryFromJSONTyped(json, false);
}

export function HistoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): History {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'paymentId': !exists(json, 'payment_id') ? undefined : json['payment_id'],
        'className': !exists(json, 'class_name') ? undefined : json['class_name'],
        'timestamp': !exists(json, 'timestamp') ? undefined : json['timestamp'],
        'total': !exists(json, 'total') ? undefined : json['total'],
        'change': !exists(json, 'change') ? undefined : json['change'],
        'product': !exists(json, 'product') ? undefined : json['product'],
    };
}

export function HistoryToJSON(value?: History | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'payment_id': value.paymentId,
        'class_name': value.className,
        'timestamp': value.timestamp,
        'total': value.total,
        'change': value.change,
        'product': value.product,
    };
}

