/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseSetting
 */
export interface ResponseSetting {
    /**
     * 
     * @type {string}
     * @memberof ResponseSetting
     */
    className: string;
    /**
     * 
     * @type {number}
     * @memberof ResponseSetting
     */
    goal: number;
    /**
     * 
     * @type {number}
     * @memberof ResponseSetting
     */
    reserve: number;

    /**
     * 
     * @type {number}
     * @memberof ResponseSetting
     */
    additionalreserve: number;
}

/**
 * Check if a given object implements the ResponseSetting interface.
 */
export function instanceOfResponseSetting(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "className" in value;
    isInstance = isInstance && "goal" in value;
    isInstance = isInstance && "reserve" in value;

    return isInstance;
}

export function ResponseSettingFromJSON(json: any): ResponseSetting {
    return ResponseSettingFromJSONTyped(json, false);
}

export function ResponseSettingFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseSetting {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'className': json['class_name'],
        'goal': json['goal'],
        'reserve': json['reserve'],
        'additionalreserve': json['additionalreserve'],
    };
}

export function ResponseSettingToJSON(value?: ResponseSetting | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'class_name': value.className,
        'goal': value.goal,
        'reserve': value.reserve,
    };
}

