/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Setting
 */
export interface Setting {
    /**
     * クラス名
     * @type {string}
     * @memberof Setting
     */
    className?: string;
    /**
     * 目標金額
     * @type {number}
     * @memberof Setting
     */
    goal?: number;
    /**
     * 準備金
     * @type {number}
     * @memberof Setting
     */
    reserve?: number;
    /**
     * 追加準備金
     * @type {number}
     * @memberof Setting
     */
    additionalreserve?: number;
}

/**
 * Check if a given object implements the Setting interface.
 */
export function instanceOfSetting(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SettingFromJSON(json: any): Setting {
    return SettingFromJSONTyped(json, false);
}

export function SettingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Setting {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'className': !exists(json, 'class_name') ? undefined : json['class_name'],
        'goal': !exists(json, 'goal') ? undefined : json['goal'],
        'reserve': !exists(json, 'reserve') ? undefined : json['reserve'],
    };
}

export function SettingToJSON(value?: Setting | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'class_name': value.className,
        'goal': value.goal,
        'reserve': value.reserve,
    };
}

