/* tslint:disable */
/* eslint-disable */
/**
 * HFHS Regi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Setting
 */
export interface Setting {
    /**
     * クラス名
     * @type {string}
     * @memberof Setting
     */
    className: string;
    /**
     * 目標金額
     * @type {number}
     * @memberof Setting
     */
    goal: number;
    /**
     * 準備金
     * @type {number}
     * @memberof Setting
     */
    reserve: number;
    /**
     * 追加準備金
     * @type {number}
     * @memberof Setting
     */
    additionalreserve: number;
}

/**
 * Check if a given object implements the Setting interface.
 */
export function instanceOfSetting(value: object): value is Setting {
    if (!('className' in value) || value['className'] === undefined) return false;
    if (!('goal' in value) || value['goal'] === undefined) return false;
    if (!('reserve' in value) || value['reserve'] === undefined) return false;
    if (!('additionalreserve' in value) || value['additionalreserve'] === undefined) return false;
    return true;
}

export function SettingFromJSON(json: any): Setting {
    return SettingFromJSONTyped(json, false);
}

export function SettingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Setting {
    if (json == null) {
        return json;
    }
    return {
        
        'className': json['class_name'],
        'goal': json['goal'],
        'reserve': json['reserve'],
        'additionalreserve': json['additionalreserve'],
    };
}

export function SettingToJSON(value?: Setting | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'class_name': value['className'],
        'goal': value['goal'],
        'reserve': value['reserve'],
        'additionalreserve': value['additionalreserve'],
    };
}

