/* tslint:disable */
/* eslint-disable */
/**
 * HFHS Regi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {string}
     * @memberof User
     */
    userMail: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    userName: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    userClass: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    userRole: string;
}

/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): value is User {
    if (!('userMail' in value) || value['userMail'] === undefined) return false;
    if (!('userName' in value) || value['userName'] === undefined) return false;
    if (!('userClass' in value) || value['userClass'] === undefined) return false;
    if (!('userRole' in value) || value['userRole'] === undefined) return false;
    return true;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if (json == null) {
        return json;
    }
    return {
        
        'userMail': json['user_mail'],
        'userName': json['user_name'],
        'userClass': json['user_class'],
        'userRole': json['user_role'],
    };
}

export function UserToJSON(value?: User | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'user_mail': value['userMail'],
        'user_name': value['userName'],
        'user_class': value['userClass'],
        'user_role': value['userRole'],
    };
}

