import Head from 'next/head'
import { Comp_Navbar } from '../../components/Navbar'
import { AppShell, Container, Title, Text, Button, rem, Flex, Grid, Table, Mark, Modal, Center, SimpleGrid, Card, Progress, Accordion, createStyles } from '@mantine/core';
import { useSession } from 'next-auth/react';


export default function History() {
    const { data: session } = useSession()
    const useStyles = createStyles((theme) => ({
        wrapper: {
            paddingTop: `calc(${theme.spacing.xl} * 2)`,
            paddingBottom: `calc(${theme.spacing.xl} * 2)`,
            minHeight: 650,
        },
        
        title: {
            marginBottom: `calc(${theme.spacing.xl} * 1.5)`,
        },
        
        item: {
            borderRadius: theme.radius.md,
            marginBottom: theme.spacing.lg,
            border: `${rem(1)} solid ${
            theme.colorScheme === 'dark' ? theme.colors.dark[4] : theme.colors.gray[3]
            }`,
        },
        }));
    return (
        <>
            <Head>
                <title>売上確認 | HFHS REGI SYS</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {
                session && (
                    <AppShell
                        navbar={<Comp_Navbar page="売上確認" username={session.user && session.user.name || "ゲスト"}/>}
                    >
                        <Title order={2}>売上確認</Title>
                        <br/>
                        <Card
                            withBorder
                            radius="md"
                            padding="xl"
                        >
                        <Text fz="xs" tt="uppercase" fw={700} c="dimmed">
                            現在の売り上げ
                        </Text>
                        <Text fz="lg" fw={500}>
                            ¥50431 / ¥100,0000
                        </Text>
                        <Progress value={50.431} mt="md" size="lg" radius="xl" />
                        </Card>
                        <br/>
                        <Title order={3}>会計履歴</Title>
                        <br/>
                        <Accordion variant="separated">
                            <Accordion.Item className="2023-05-24-13-50" value="history_1">
                            <Accordion.Control>5月24日 11時50分</Accordion.Control>
                            <Accordion.Panel>
                            <Table miw={700}>
                                <thead className="tekitou">
                                <tr>
                                    <th>購入日時</th>
                                    <th>購入商品</th>
                                    <th>金額</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr key="5_24_11_50">
                                    <td>5月24日 11時50分</td>
                                    <td>かき氷1</td>
                                    <td>200円(預かり金: 500円 / お釣り: 300円)</td>
                                </tr>
                                </tbody>
                            </Table>
                            </Accordion.Panel>
                            </Accordion.Item>
                        </Accordion>
                    </AppShell>
                )
            }
        </>
    )
}