import Head from 'next/head'
import { Comp_Navbar } from '../components/Navbar'
import { useSession } from 'next-auth/react';
import { AppShell, Container, Title, Text, Button, rem, Flex, Grid, Table } from '@mantine/core';
import { IconBrandGoogle } from '@tabler/icons-react';
import { signIn } from 'next-auth/react';
import productsByClass from './utils/product';

export default function Home() {
    const { data: session, status } = useSession()
    const products = productsByClass["2年1組"].map((element) => (
        <tr key={element.id}>
            <Button size={ "xl" }>{ element.name }</Button>
        </tr>
    ));
    return (
        <>
            <Head>
                <title>HFHS REGI SYS</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {
                session && (
                    <AppShell
                        navbar={<Comp_Navbar page="会計" username={session.user && session.user.name || "ゲスト"}/>}
                    >
                        <Grid grow>
                            <Grid.Col span={2}>
                                <Flex
                                    mih={50}
                                    gap="sm"
                                    justify="flex-end"
                                    align="center"
                                    direction="column"
                                    wrap="wrap"
                                >
                                    <Title order={4}>商品一覧</Title>
                                    {products}
                                </Flex>
                            </Grid.Col>
                            <Grid.Col span={10}>
                                <Flex
                                    mih={50}
                                    gap="sm"
                                    justify="flex-end"
                                    align="center"
                                    direction="column"
                                    wrap="wrap"
                                >
                                    <Title order={5}>購入商品</Title>
                                    <Table verticalSpacing="xs">
                                    <thead>
                                        <tr>
                                        <th>商品</th>
                                        <th>値段</th>
                                        <th>個数</th>
                                        <th>操作</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr key="Name01">
                                        <td>かき氷</td>
                                        <td>¥300</td>
                                        <td>1つ</td>
                                        <td><a>削除</a></td>
                                        </tr>
                                    </tbody>
                                    </Table>
                                </Flex>
                            </Grid.Col>
                        </Grid>
                    </AppShell>
                )
            }
            {
                !session && (
                    <Container
                        sx={{
                            display: "flex",
                            flexDirection: "column",
                            height: "100vh",
                            justifyContent: "center",
                            alignItems: "center",
                        }}
                    >
                        <Title order={2}>ログイン</Title>
                        <Text>学校のGoogleアカウントを使って、ログインしてください。</Text>
                        <Button
                            leftIcon={
                                <IconBrandGoogle size="1.2rem" stroke={1.5} />
                            }
                            radius="xl"
                            size="md"
                            styles={{
                            root: { paddingRight: rem(14), height: rem(48) },
                            }}
                            onClick={() => signIn()}
                        >
                            Googleでログイン
                        </Button>
                    </Container>
                )
            }
        </>
    )
}
function useState(arg0: never[]): [any, any] {
    throw new Error('Function not implemented.');
}

