import React from 'react';
import { useSession, signIn, signOut } from 'next-auth/react';
import { NextPage } from 'next';
import { Comp_Navbar } from '../components/Navbar';
import Head from "next/head";

export default function Login() {
    const { data: session } = useSession()
    return (
        <>
            <Head>
                <title>ログイン | HFHS REGI SYS</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {
                // セッションがある場合、ログアウトを表示
                session && (
                <div>
                    <h1>ようこそ, {session.user && session.user.email}</h1>
                    <button onClick={() => signOut()}>ログアウト</button>
                </div>
                )
            }
            {
                // セッションがない場合、ログインを表示
                // ログインボタンを押すと、ログインページに遷移する
                !session && (
                <div>
                    <p>ログインしていません</p>
                    <button onClick={() => signIn()}>ログイン</button>
                </div>
                )
            }
        </>
    )
  }