import Head from 'next/head'
import { Comp_Navbar } from '../../components/Navbar'
import { AppShell, Container, Title, Text, Button, rem, Flex, Grid, Table, Mark, Modal, Center, SimpleGrid, Card, Progress, Accordion, createStyles, TextInput, NumberInput } from '@mantine/core';
import { useSession } from 'next-auth/react';


export default function History() {
    const { data: session } = useSession()
    const useStyles = createStyles((theme) => ({
        wrapper: {
            paddingTop: `calc(${theme.spacing.xl} * 2)`,
            paddingBottom: `calc(${theme.spacing.xl} * 2)`,
            minHeight: 650,
        },
        
        title: {
            marginBottom: `calc(${theme.spacing.xl} * 1.5)`,
        },
        
        item: {
            borderRadius: theme.radius.md,
            marginBottom: theme.spacing.lg,
            border: `${rem(1)} solid ${
            theme.colorScheme === 'dark' ? theme.colors.dark[4] : theme.colors.gray[3]
            }`,
        },
        }));
    return (
        <>
            <Head>
                <title>店舗設定 | HFHS REGI SYS</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {
                session && (
                    <AppShell
                        navbar={<Comp_Navbar page="店舗設定" username={session.user && session.user.name || "ゲスト"} storeName="デモ | HFHS REGI"/>}
                    >
                        <Title order={2}>店舗設定</Title>
                        <br/>
                        <Title order={3}>目標売り上げ</Title>
                        <Text>ここでの目標売上は、1日での売上額を指定してください。売上確認ページに反映されます。</Text>
                        <NumberInput size="sm" label="目標売り上げ" placeholder="50,000円" className=""/>
                        <br/>
                        <Title order={3}>準備金</Title>
                        <Text>生徒と先生の準備金の合計を入力してください。</Text>
                        <NumberInput size="sm" label="準備金" placeholder="50,000円" className="" />
                        <br/>
                        <Center>
                            <Button size={ "md" }>保存</Button>
                        </Center>
                    </AppShell>
                )
            }
        </>
    )
}