/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HistoryAdd
 */
export interface HistoryAdd {
    /**
     * クラス名
     * @type {string}
     * @memberof HistoryAdd
     */
    className?: string;
    /**
     * 購入金額
     * @type {number}
     * @memberof HistoryAdd
     */
    total?: number;
    /**
     * お釣り
     * @type {number}
     * @memberof HistoryAdd
     */
    change?: number;
    /**
     * 購入商品
     * @type {string}
     * @memberof HistoryAdd
     */
    product?: string;
}

/**
 * Check if a given object implements the HistoryAdd interface.
 */
export function instanceOfHistoryAdd(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HistoryAddFromJSON(json: any): HistoryAdd {
    return HistoryAddFromJSONTyped(json, false);
}

export function HistoryAddFromJSONTyped(json: any, ignoreDiscriminator: boolean): HistoryAdd {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'className': !exists(json, 'class_name') ? undefined : json['class_name'],
        'total': !exists(json, 'total') ? undefined : json['total'],
        'change': !exists(json, 'change') ? undefined : json['change'],
        'product': !exists(json, 'product') ? undefined : json['product'],
    };
}

export function HistoryAddToJSON(value?: HistoryAdd | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'class_name': value.className,
        'total': value.total,
        'change': value.change,
        'product': value.product,
    };
}

