/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseUser
 */
export interface ResponseUser {
    /**
     * 
     * @type {string}
     * @memberof ResponseUser
     */
    userMail: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseUser
     */
    userName: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseUser
     */
    userClass: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseUser
     */
    userRole: string;
}

/**
 * Check if a given object implements the ResponseUser interface.
 */
export function instanceOfResponseUser(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "userMail" in value;
    isInstance = isInstance && "userName" in value;
    isInstance = isInstance && "userClass" in value;
    isInstance = isInstance && "userRole" in value;

    return isInstance;
}

export function ResponseUserFromJSON(json: any): ResponseUser {
    return ResponseUserFromJSONTyped(json, false);
}

export function ResponseUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userMail': json['user_mail'],
        'userName': json['user_name'],
        'userClass': json['user_class'],
        'userRole': json['user_role'],
    };
}

export function ResponseUserToJSON(value?: ResponseUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user_mail': value.userMail,
        'user_name': value.userName,
        'user_class': value.userClass,
        'user_role': value.userRole,
    };
}

